import JSZip from 'jszip';
import { GeneratedReactFiles } from '@/types/react-generation';

// Helper to reliably map React Sandbox files -> Vite files
const VITE_PACKAGE_JSON = {
  name: "react-project",
  version: "0.1.0",
  private: true,
  scripts: {
    dev: "vite",
    build: "vite build",
    preview: "vite preview"
  },
  dependencies: {
    react: "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.0",
    "lucide-react": "^0.344.0"
  },
  devDependencies: {
    "@vitejs/plugin-react": "^4.2.1",
    vite: "^5.1.4"
  }
};

const VITE_CONFIG_JS = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
})
`;

const processViteFiles = (files: GeneratedReactFiles) => {
  const zip = new JSZip();
  
  zip.file("package.json", JSON.stringify(VITE_PACKAGE_JSON, null, 2));
  zip.file("vite.config.js", VITE_CONFIG_JS);
  
  const srcFolder = zip.folder("src")!;
  
  // Keep track of index html to inject module script
  let indexHtml = files["/public/index.html"] || `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`;

  if (!indexHtml.includes('<script type="module" src="/src/index.jsx"></script>')) {
    indexHtml = indexHtml.replace('</body>', '  <script type="module" src="/src/index.jsx"></script>\n  </body>');
  }
  zip.file("index.html", indexHtml);
  
  for (const [path, content] of Object.entries(files)) {
    if (path === "/public/index.html") continue;
    
    // Everything else maps to src/
    let localPath = path.startsWith('/') ? path.slice(1) : path;
    
    // Vite strictly requires .jsx for JSX files. Rename .js down to .jsx.
    if (localPath.endsWith(".js")) {
        localPath = localPath.replace(/\.js$/, ".jsx");
    }
    
    srcFolder.file(localPath, content as string);
  }

  return zip;
};

// Map Sandbox files -> Next.js App Router files
const NEXTJS_PACKAGE_JSON = {
  name: "nextjs-project",
  version: "0.1.0",
  private: true,
  scripts: {
    dev: "next dev",
    build: "next build",
    start: "next start",
    lint: "next lint"
  },
  dependencies: {
    react: "^18.2.0",
    "react-dom": "^18.2.0",
    next: "14.1.3",
    "lucide-react": "^0.344.0",
    "react-router-dom": "^6.22.0"
  },
  devDependencies: {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    autoprefixer: "^10.0.1",
    postcss: "^8",
    tailwindcss: "^3.3.0",
    typescript: "^5"
  }
};

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
`;

const TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;

const POSTCSS_CONFIG = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

const processNextjsFiles = (files: GeneratedReactFiles) => {
  const zip = new JSZip();
  
  zip.file("package.json", JSON.stringify(NEXTJS_PACKAGE_JSON, null, 2));
  zip.file("next.config.mjs", NEXT_CONFIG);
  zip.file("tailwind.config.js", TAILWIND_CONFIG);
  zip.file("postcss.config.js", POSTCSS_CONFIG);
  
  // Extract custom fonts from public/index.html
  let fontLinks = "";
  if (files["/public/index.html"]) {
     const match = files["/public/index.html"].match(/<link[^>]*href="https:\/\/fonts[^>]*>/g);
     if (match) fontLinks = match.join("\\n        ");
  }

  const srcFolder = zip.folder("src")!;
  const appFolder = srcFolder.folder("app")!;
  
  appFolder.file("layout.tsx", `import "../styles.css";

export const metadata = {
  title: "Next.js Application",
  description: "Generated by AI Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        ${fontLinks}
      </head>
      <body>{children}</body>
    </html>
  )
}
`);

  appFolder.file("page.tsx", `"use client";
import React, { useEffect, useState } from "react";
import App from "../App";

// Wrapped App to ensure client-side rendering for browser-router elements
export default function Home() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;
  return <App />;
}
`);

  for (const [path, content] of Object.entries(files)) {
    if (path === "/public/index.html") continue;
    if (path === "/index.js") continue; // NextJS doesn't need the React DOM mount entrypoint
    
    let localPath = path.startsWith('/') ? path.slice(1) : path;
    
    if (localPath.endsWith(".js")) {
        localPath = localPath.replace(/\.js$/, ".jsx");
    }

    srcFolder.file(localPath, content as string);
  }

  return zip;
};

export const saveBlobAsFile = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

export const exportAsReact = async (files: GeneratedReactFiles) => {
  const zip = processViteFiles(files);
  const content = await zip.generateAsync({ type: "blob" });
  saveBlobAsFile(content, "react-vite-project.zip");
};

export const exportAsNextjs = async (files: GeneratedReactFiles) => {
  const zip = processNextjsFiles(files);
  const content = await zip.generateAsync({ type: "blob" });
  saveBlobAsFile(content, "nextjs-project.zip");
};
